# Generated by Django 4.2.1 on 2023-06-05 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(choices=[('small', 'Small - Under 3Kg'), ('medium', 'Medium - Under 10Kg'), ('large', 'Large - Over 10Kg')], default='small', max_length=200)),
                ('doacao_slug', models.SlugField(unique=True, verbose_name='Doacao Slug')),
                ('published', models.DateTimeField(default=datetime.datetime(2023, 6, 5, 4, 7, 3, 2930, tzinfo=datetime.timezone.utc), verbose_name='Date published')),
                ('modified', models.DateTimeField(default=datetime.datetime(2023, 6, 5, 4, 7, 3, 2930, tzinfo=datetime.timezone.utc), verbose_name='Date modified')),
            ],
            options={
                'verbose_name_plural': 'Doacao',
                'ordering': ['title', '-published'],
            },
        ),
        migrations.CreateModel(
            name='DoacaoSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', max_length=200)),
                ('slug', models.SlugField(unique=True, verbose_name='Series Slug')),
                ('published', models.DateTimeField(default=datetime.datetime(2023, 6, 5, 4, 7, 3, 1440, tzinfo=datetime.timezone.utc), verbose_name='Date published')),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ['-published'],
            },
        ),
    ]
