# Generated by Django 4.2.1 on 2023-06-05 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_doacao_endereco_alter_doacao_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 18, 59, 55, 225772, tzinfo=datetime.timezone.utc), verbose_name='Date modified'),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 18, 59, 55, 225772, tzinfo=datetime.timezone.utc), verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='doacaoseries',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 18, 59, 55, 224283, tzinfo=datetime.timezone.utc), verbose_name='Date published'),
        ),
    ]
