# Generated by Django 4.2.1 on 2023-06-05 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_doacao_modified_alter_doacao_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 19, 55, 57, 472439, tzinfo=datetime.timezone.utc), verbose_name='Date modified'),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 19, 55, 57, 472439, tzinfo=datetime.timezone.utc), verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='doacaoseries',
            name='author',
            field=models.CharField(default='Admin', max_length=200),
        ),
        migrations.AlterField(
            model_name='doacaoseries',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 19, 55, 57, 471944, tzinfo=datetime.timezone.utc), verbose_name='Date published'),
        ),
    ]
