# Generated by Django 4.2.1 on 2023-06-05 20:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_doacao_modified_alter_doacao_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 20, 0, 1, 537748, tzinfo=datetime.timezone.utc), verbose_name='Date modified'),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 20, 0, 1, 537748, tzinfo=datetime.timezone.utc), verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='doacaoseries',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doacaoseries',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 20, 0, 1, 537252, tzinfo=datetime.timezone.utc), verbose_name='Date published'),
        ),
    ]
